/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PropfirmsRouteImport } from './routes/propfirms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as LiveTradingRouteImport } from './routes/live-trading'
import { Route as IndicatorsRouteImport } from './routes/indicators'
import { Route as EducationRouteImport } from './routes/education'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscordCallbackRouteImport } from './routes/discord.callback'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PropfirmsRoute = PropfirmsRouteImport.update({
  id: '/propfirms',
  path: '/propfirms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTradingRoute = LiveTradingRouteImport.update({
  id: '/live-trading',
  path: '/live-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicatorsRoute = IndicatorsRouteImport.update({
  id: '/indicators',
  path: '/indicators',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordCallbackRoute = DiscordCallbackRouteImport.update({
  id: '/discord/callback',
  path: '/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/education': typeof EducationRoute
  '/indicators': typeof IndicatorsRoute
  '/live-trading': typeof LiveTradingRoute
  '/mentorship': typeof MentorshipRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/propfirms': typeof PropfirmsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/discord/callback': typeof DiscordCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/education': typeof EducationRoute
  '/indicators': typeof IndicatorsRoute
  '/live-trading': typeof LiveTradingRoute
  '/mentorship': typeof MentorshipRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/propfirms': typeof PropfirmsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/discord/callback': typeof DiscordCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/education': typeof EducationRoute
  '/indicators': typeof IndicatorsRoute
  '/live-trading': typeof LiveTradingRoute
  '/mentorship': typeof MentorshipRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/propfirms': typeof PropfirmsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/discord/callback': typeof DiscordCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/education'
    | '/indicators'
    | '/live-trading'
    | '/mentorship'
    | '/news'
    | '/privacy-policy'
    | '/propfirms'
    | '/refund-policy'
    | '/terms-of-service'
    | '/blog/$slug'
    | '/discord/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/education'
    | '/indicators'
    | '/live-trading'
    | '/mentorship'
    | '/news'
    | '/privacy-policy'
    | '/propfirms'
    | '/refund-policy'
    | '/terms-of-service'
    | '/blog/$slug'
    | '/discord/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/education'
    | '/indicators'
    | '/live-trading'
    | '/mentorship'
    | '/news'
    | '/privacy-policy'
    | '/propfirms'
    | '/refund-policy'
    | '/terms-of-service'
    | '/blog_/$slug'
    | '/discord/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  EducationRoute: typeof EducationRoute
  IndicatorsRoute: typeof IndicatorsRoute
  LiveTradingRoute: typeof LiveTradingRoute
  MentorshipRoute: typeof MentorshipRoute
  NewsRoute: typeof NewsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PropfirmsRoute: typeof PropfirmsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DiscordCallbackRoute: typeof DiscordCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propfirms': {
      id: '/propfirms'
      path: '/propfirms'
      fullPath: '/propfirms'
      preLoaderRoute: typeof PropfirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-trading': {
      id: '/live-trading'
      path: '/live-trading'
      fullPath: '/live-trading'
      preLoaderRoute: typeof LiveTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicators': {
      id: '/indicators'
      path: '/indicators'
      fullPath: '/indicators'
      preLoaderRoute: typeof IndicatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord/callback': {
      id: '/discord/callback'
      path: '/discord/callback'
      fullPath: '/discord/callback'
      preLoaderRoute: typeof DiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  EducationRoute: EducationRoute,
  IndicatorsRoute: IndicatorsRoute,
  LiveTradingRoute: LiveTradingRoute,
  MentorshipRoute: MentorshipRoute,
  NewsRoute: NewsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PropfirmsRoute: PropfirmsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  BlogSlugRoute: BlogSlugRoute,
  DiscordCallbackRoute: DiscordCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
