/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PropfirmsRouteImport } from './routes/propfirms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as LiveTradingRouteImport } from './routes/live-trading'
import { Route as IndicatorsRouteImport } from './routes/indicators'
import { Route as EducationRouteImport } from './routes/education'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PaymentFailureRouteImport } from './routes/payment.failure'
import { Route as PaymentCancelRouteImport } from './routes/payment.cancel'
import { Route as EducationSlugRouteImport } from './routes/education_.$slug'
import { Route as DiscordCallbackRouteImport } from './routes/discord.callback'
import { Route as AdminEducationNewRouteImport } from './routes/admin_.education.new'
import { Route as AdminEducationEditSlugRouteImport } from './routes/admin_.education.edit.$slug'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PropfirmsRoute = PropfirmsRouteImport.update({
  id: '/propfirms',
  path: '/propfirms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTradingRoute = LiveTradingRouteImport.update({
  id: '/live-trading',
  path: '/live-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicatorsRoute = IndicatorsRouteImport.update({
  id: '/indicators',
  path: '/indicators',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailureRoute = PaymentFailureRouteImport.update({
  id: '/payment/failure',
  path: '/payment/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationSlugRoute = EducationSlugRouteImport.update({
  id: '/education_/$slug',
  path: '/education/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordCallbackRoute = DiscordCallbackRouteImport.update({
  id: '/discord/callback',
  path: '/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEducationNewRoute = AdminEducationNewRouteImport.update({
  id: '/admin_/education/new',
  path: '/admin/education/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEducationEditSlugRoute = AdminEducationEditSlugRouteImport.update({
  id: '/admin_/education/edit/$slug',
  path: '/admin/education/edit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/education': typeof EducationRoute
  '/indicators': typeof IndicatorsRoute
  '/live-trading': typeof LiveTradingRoute
  '/mentorship': typeof MentorshipRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/propfirms': typeof PropfirmsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/discord/callback': typeof DiscordCallbackRoute
  '/education/$slug': typeof EducationSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin/education/new': typeof AdminEducationNewRoute
  '/admin/education/edit/$slug': typeof AdminEducationEditSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/education': typeof EducationRoute
  '/indicators': typeof IndicatorsRoute
  '/live-trading': typeof LiveTradingRoute
  '/mentorship': typeof MentorshipRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/propfirms': typeof PropfirmsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/discord/callback': typeof DiscordCallbackRoute
  '/education/$slug': typeof EducationSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin/education/new': typeof AdminEducationNewRoute
  '/admin/education/edit/$slug': typeof AdminEducationEditSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/education': typeof EducationRoute
  '/indicators': typeof IndicatorsRoute
  '/live-trading': typeof LiveTradingRoute
  '/mentorship': typeof MentorshipRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/propfirms': typeof PropfirmsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/discord/callback': typeof DiscordCallbackRoute
  '/education_/$slug': typeof EducationSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin_/education/new': typeof AdminEducationNewRoute
  '/admin_/education/edit/$slug': typeof AdminEducationEditSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/education'
    | '/indicators'
    | '/live-trading'
    | '/mentorship'
    | '/news'
    | '/privacy-policy'
    | '/propfirms'
    | '/refund-policy'
    | '/reset-password'
    | '/terms-of-service'
    | '/discord/callback'
    | '/education/$slug'
    | '/payment/cancel'
    | '/payment/failure'
    | '/payment/success'
    | '/admin/education/new'
    | '/admin/education/edit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/education'
    | '/indicators'
    | '/live-trading'
    | '/mentorship'
    | '/news'
    | '/privacy-policy'
    | '/propfirms'
    | '/refund-policy'
    | '/reset-password'
    | '/terms-of-service'
    | '/discord/callback'
    | '/education/$slug'
    | '/payment/cancel'
    | '/payment/failure'
    | '/payment/success'
    | '/admin/education/new'
    | '/admin/education/edit/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/education'
    | '/indicators'
    | '/live-trading'
    | '/mentorship'
    | '/news'
    | '/privacy-policy'
    | '/propfirms'
    | '/refund-policy'
    | '/reset-password'
    | '/terms-of-service'
    | '/discord/callback'
    | '/education_/$slug'
    | '/payment/cancel'
    | '/payment/failure'
    | '/payment/success'
    | '/admin_/education/new'
    | '/admin_/education/edit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  EducationRoute: typeof EducationRoute
  IndicatorsRoute: typeof IndicatorsRoute
  LiveTradingRoute: typeof LiveTradingRoute
  MentorshipRoute: typeof MentorshipRoute
  NewsRoute: typeof NewsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PropfirmsRoute: typeof PropfirmsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  DiscordCallbackRoute: typeof DiscordCallbackRoute
  EducationSlugRoute: typeof EducationSlugRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentFailureRoute: typeof PaymentFailureRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  AdminEducationNewRoute: typeof AdminEducationNewRoute
  AdminEducationEditSlugRoute: typeof AdminEducationEditSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propfirms': {
      id: '/propfirms'
      path: '/propfirms'
      fullPath: '/propfirms'
      preLoaderRoute: typeof PropfirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-trading': {
      id: '/live-trading'
      path: '/live-trading'
      fullPath: '/live-trading'
      preLoaderRoute: typeof LiveTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicators': {
      id: '/indicators'
      path: '/indicators'
      fullPath: '/indicators'
      preLoaderRoute: typeof IndicatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failure': {
      id: '/payment/failure'
      path: '/payment/failure'
      fullPath: '/payment/failure'
      preLoaderRoute: typeof PaymentFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education_/$slug': {
      id: '/education_/$slug'
      path: '/education/$slug'
      fullPath: '/education/$slug'
      preLoaderRoute: typeof EducationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord/callback': {
      id: '/discord/callback'
      path: '/discord/callback'
      fullPath: '/discord/callback'
      preLoaderRoute: typeof DiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/education/new': {
      id: '/admin_/education/new'
      path: '/admin/education/new'
      fullPath: '/admin/education/new'
      preLoaderRoute: typeof AdminEducationNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/education/edit/$slug': {
      id: '/admin_/education/edit/$slug'
      path: '/admin/education/edit/$slug'
      fullPath: '/admin/education/edit/$slug'
      preLoaderRoute: typeof AdminEducationEditSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  EducationRoute: EducationRoute,
  IndicatorsRoute: IndicatorsRoute,
  LiveTradingRoute: LiveTradingRoute,
  MentorshipRoute: MentorshipRoute,
  NewsRoute: NewsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PropfirmsRoute: PropfirmsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  DiscordCallbackRoute: DiscordCallbackRoute,
  EducationSlugRoute: EducationSlugRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentFailureRoute: PaymentFailureRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  AdminEducationNewRoute: AdminEducationNewRoute,
  AdminEducationEditSlugRoute: AdminEducationEditSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
