-- Keep the backend prop firm catalog limited to the approved ZacTrades partners.
delete from public.prop_firms
where slug not in (
  'alpha-futures',
  'earn2trade',
  'fundednext',
  'alpha-capital-group',
  'funding-pips'
);

insert into public.prop_firms (
  slug,
  name,
  description,
  logo,
  discount,
  promo_code,
  color,
  rating,
  reviews,
  max_capital,
  profit_split,
  payout,
  features,
  url,
  is_featured,
  is_active,
  display_order
)
values
  (
    'alpha-futures',
    'Alpha Futures',
    'Futures funding platform for traders who want structured evaluation access.',
    'AF',
    'Max Discount',
    'ZACTRADES',
    '#22c55e',
    4.4,
    3200,
    '$150K',
    '90%',
    'Bi-weekly',
    array['TV', 'Web'],
    'https://app.alpha-futures.com',
    true,
    true,
    1
  ),
  (
    'earn2trade',
    'Earn2Trade',
    'Education-first futures evaluation platform with structured trader development.',
    'E2T',
    'Max Discount',
    'ZACTRADES',
    '#38bdf8',
    4.4,
    4100,
    '$200K',
    '80%',
    'Monthly',
    array['TV', 'Web'],
    'https://www.earn2trade.com',
    true,
    true,
    2
  ),
  (
    'fundednext',
    'FundedNext',
    'Multi-asset prop firm with flexible challenges and a modern trader dashboard.',
    'FN',
    'Max Discount',
    'ZACTRADES',
    '#ec4899',
    4.3,
    6700,
    '$200K',
    '95%',
    'Bi-weekly',
    array['MT5', 'App', 'Web'],
    'https://app.fundednext.com',
    true,
    true,
    3
  ),
  (
    'alpha-capital-group',
    'Alpha Capital Group',
    'Professional prop trading firm with challenge accounts and scaling opportunities.',
    'ACG',
    'Max Discount',
    'ZACTRADES',
    '#a855f7',
    4.4,
    2800,
    '$200K',
    '80%',
    'Bi-weekly',
    array['MT5', 'Web'],
    'https://app.alphacapitalgroup.uk',
    false,
    true,
    4
  ),
  (
    'funding-pips',
    'Funding Pips',
    'Popular prop firm for forex traders with flexible rules and fast account access.',
    'FP',
    'Max Discount',
    'ZACTRADES',
    '#f59e0b',
    4.2,
    5200,
    '$100K',
    '80%',
    'Bi-weekly',
    array['MT5', 'Web'],
    'https://app.fundingpips.com',
    false,
    true,
    5
  )
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  logo = excluded.logo,
  discount = excluded.discount,
  promo_code = excluded.promo_code,
  color = excluded.color,
  rating = excluded.rating,
  reviews = excluded.reviews,
  max_capital = excluded.max_capital,
  profit_split = excluded.profit_split,
  payout = excluded.payout,
  features = excluded.features,
  url = excluded.url,
  is_featured = excluded.is_featured,
  is_active = excluded.is_active,
  display_order = excluded.display_order,
  updated_at = now();
